name: ci

on:
  push:
    branches:
      - 'GitActions'

jobs:
  Forontend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Fe
        uses: docker/build-push-action@v5
        with:
          file: ./Fe/Dockerfile
          push: true
          tags:  leo42/broclan:latest 
  ImageGenerator:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ImageGenerator
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}/Be/imageGenerator"
          push: true
          tags:  leo42/image_generator:latest
  Indexer:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Indexer 
        uses: docker/build-push-action@v5
        with:
          file: ./Be/indexer/Dockerfile
          push: true
          tags:  leo42/indexer:latest
  tokenApi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push token_api 
        uses: docker/build-push-action@v5
        with:
          context: "/Be/tokenApi"
          push: true
          tags:  leo42/token_api:latest
  passthrough:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push Blockfrost passthrough
        uses: docker/build-push-action@v5
        with:
          push: true
          tags:  leo42/passthrough:latest
          context: Be/passthrough 
          file: Be/passthrough/Dockerfile