on:
  push:
    tags:
      - 'v*'

jobs:
  Frontend:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Debug RELEASE_TAG
        run: echo "RELEASE_TAG=${{ env.RELEASE_TAG }}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Fe
        uses: docker/build-push-action@v5
        with:
          file: ./Fe/Dockerfile
          push: true
          tags:  leo42/broclan:${{ steps.meta.outputs.tags }} 
  ImageGenerator:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ImageGenerator
        uses: docker/build-push-action@v5
        with:
          file: ./Be/imageGenerator/Dockerfile
          push: true
          tags:  leo42/image_generator:${{ steps.meta.outputs.tags }}
  Indexer:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Indexer 
        uses: docker/build-push-action@v5
        with:
          file: ./Be/indexer/Dockerfile
          push: true
          tags:  leo42/indexer:${{ steps.meta.outputs.tags }}
  tokenApi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push token_api 
        uses: docker/build-push-action@v5
        with:
          file: "./Be/tokenApi/Dockerfile"
          push: true
          tags:  leo42/token_api:${{ steps.meta.outputs.tags }}
  passthrough:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push Blockfrost passthrough
        uses: docker/build-push-action@v5
        with:
          file: ./Be/passthrough/Dockerfile
          push: true
          tags:  leo42/passthrough:${{ env.RELEASE_TAG }}